# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build configuration
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_create_environment:
      # Install latest pip for better dependency resolution
      - pip install --upgrade pip setuptools wheel
    post_install:
      # Show installed packages for debugging
      - pip list

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Python dependencies
python:
  install:
    - requirements: docs/requirements.txt

# Build formats (PDF, ePub, etc.)
formats:
  - pdf
  - epub

# Search configuration
search:
  ranking:
    api/*: -1
  ignore:
    - 404.html